/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FITFSKEWED
#define FITFSKEWED

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class fitFskewed : public RooAbsPdf {
public:
  fitFskewed() {} ; 
  fitFskewed(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sig1,
	      RooAbsReal& _sig2);
  fitFskewed(const fitFskewed& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new fitFskewed(*this,newname); }
  inline virtual ~fitFskewed() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sig1 ;
  RooRealProxy sig2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(fitFskewed,1) // Your description goes here...
};
 
#endif
