/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FITFP2N
#define FITFP2N

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class fitFp2n : public RooAbsPdf {
public:
  fitFp2n() {} ; 
  fitFp2n(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _l0,
	      RooAbsReal& _p1n,
	      RooAbsReal& _p2n);
  fitFp2n(const fitFp2n& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new fitFp2n(*this,newname); }
  inline virtual ~fitFp2n() { }

protected:

  RooRealProxy x ;
  RooRealProxy l0 ;
  RooRealProxy p1n ;
  RooRealProxy p2n ;
  
  Double_t evaluate() const ;

private:

  ClassDef(fitFp2n,1) // Your description goes here...
};
 
#endif
