/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "fitFp2n.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(fitFp2n) 

 fitFp2n::fitFp2n(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _l0,
                        RooAbsReal& _p1n,
                        RooAbsReal& _p2n) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   l0("l0","l0",this,_l0),
   p1n("p1n","p1n",this,_p1n),
   p2n("p2n","p2n",this,_p2n)
 { 
 } 


 fitFp2n::fitFp2n(const fitFp2n& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   l0("l0",this,other.l0),
   p1n("p1n",this,other.p1n),
   p2n("p2n",this,other.p2n)
 { 
 } 



 Double_t fitFp2n::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return p1n*p2n*l0*exp(-l0*x) ; 
 } 



