/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FITFP1N
#define FITFP1N

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class fitFp1n : public RooAbsPdf {
public:
  fitFp1n() {} ; 
  fitFp1n(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _l0,
	      RooAbsReal& _p1n);
  fitFp1n(const fitFp1n& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new fitFp1n(*this,newname); }
  inline virtual ~fitFp1n() { }

protected:

  RooRealProxy x ;
  RooRealProxy l0 ;
  RooRealProxy p1n ;
  
  Double_t evaluate() const ;

private:

  ClassDef(fitFp1n,1) // Your description goes here...
};
 
#endif
