/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "fitF.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(fitF) 

 fitF::fitF(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _l0) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   l0("l0","l0",this,_l0)
 { 
 } 


 fitF::fitF(const fitF& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   l0("l0",this,other.l0)
 { 
 } 



 Double_t fitF::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return l0*exp(-l0*x) ; 
 } 



