/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "fitFp1n.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(fitFp1n) 

 fitFp1n::fitFp1n(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _l0,
                        RooAbsReal& _p1n) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   l0("l0","l0",this,_l0),
   p1n("p1n","p1n",this,_p1n)
 { 
 } 


 fitFp1n::fitFp1n(const fitFp1n& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   l0("l0",this,other.l0),
   p1n("p1n",this,other.p1n)
 { 
 } 



 Double_t fitFp1n::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return p1n*l0*exp(-l0*x) ; 
 } 



