/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef FITF
#define FITF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class fitF : public RooAbsPdf {
public:
  fitF() {} ;
  fitF(const char *name, const char *title,
              RooAbsReal& _x, RooAbsCategory &_y,
              RooAbsReal& _l0, RooAbsReal &_p1n, RooAbsReal &_p2n);
  fitF(const fitF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new fitF(*this,newname); }
  inline virtual ~fitF() { }

protected:

  RooRealProxy x ;
  RooCategoryProxy y ;
  RooRealProxy l0 ;
  RooRealProxy p1n ;
  RooRealProxy p2n ;

  Double_t evaluate() const ;

private:

  ClassDef(fitF,1) // Your description goes here...
};

#endif
