./offlinemakemlhtree.sh list/listlowin.txt Sn134 /home/phong/briken17/results/fithistograms/Sn134lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Sn135 /home/phong/briken17/results/fithistograms/Sn135lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Sn136 /home/phong/briken17/results/fithistograms/Sn136lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Sn137 /home/phong/briken17/results/fithistograms/Sn137lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Sn138 /home/phong/briken17/results/fithistograms/Sn138lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Sn139 /home/phong/briken17/results/fithistograms/Sn139lowin.root
./offlinemakemlhtree.sh list/listlowin.txt In131 /home/phong/briken17/results/fithistograms/In131lowin.root
./offlinemakemlhtree.sh list/listlowin.txt In132 /home/phong/briken17/results/fithistograms/In132lowin.root
./offlinemakemlhtree.sh list/listlowin.txt In133 /home/phong/briken17/results/fithistograms/In133lowin.root
./offlinemakemlhtree.sh list/listlowin.txt In134 /home/phong/briken17/results/fithistograms/In134lowin.root
./offlinemakemlhtree.sh list/listlowin.txt In135 /home/phong/briken17/results/fithistograms/In135lowin.root
./offlinemakemlhtree.sh list/listlowin.txt In136 /home/phong/briken17/results/fithistograms/In136lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Cd131 /home/phong/briken17/results/fithistograms/Cd131lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Cd132 /home/phong/briken17/results/fithistograms/Cd132lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Cd133 /home/phong/briken17/results/fithistograms/Cd133lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Cd134 /home/phong/briken17/results/fithistograms/Cd134lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Ag129 /home/phong/briken17/results/fithistograms/Ag129lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Ag130 /home/phong/briken17/results/fithistograms/Ag130lowin.root
./offlinemakemlhtree.sh list/listlowin.txt Ag131 /home/phong/briken17/results/fithistograms/Ag131lowin.root
